### ISSUE TITLE
incomplete

### ISSUE THREAD

**Issue by mschneider82** [chennqqi/nsqbeat#1]
Hi 

since this project is incomplete and only the beat template i created a new one with the same name:

https://github.com/mschneider82/nsqbeat

nsq is implemented. I think you can remove this repo and fork mine if you want to change something!

Best regards

**Comment by chennqqi** [comment]
Thankyou. My origin perpose just to write out(beat) to NSQ... So this repo <https://github.com/chennqqi/filebeat.nsq.output>
is my final goal..
I'ill close this repo
